# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/andrew/Documents/Unreal 4/UnrealEngine-4.27-plus
GAMEPROJECTFILE =/home/andrew/Documents/Unreal Projects/GPE230_AndrewLong/GPE230_AndrewLong.uproject

TARGETS = \
	GPE230_AndrewLong-Linux-Debug  \
	GPE230_AndrewLong-Linux-DebugGame  \
	GPE230_AndrewLong-Linux-Shipping  \
	GPE230_AndrewLong-Linux-Test  \
	GPE230_AndrewLong \
	GPE230_AndrewLongEditor-Linux-Debug  \
	GPE230_AndrewLongEditor-Linux-DebugGame  \
	GPE230_AndrewLongEditor-Linux-Shipping  \
	GPE230_AndrewLongEditor-Linux-Test  \
	GPE230_AndrewLongEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


GPE230_AndrewLong-Linux-Debug:
	 $(PROJECTBUILD) GPE230_AndrewLong Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLong-Linux-DebugGame:
	 $(PROJECTBUILD) GPE230_AndrewLong Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLong-Linux-Shipping:
	 $(PROJECTBUILD) GPE230_AndrewLong Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLong-Linux-Test:
	 $(PROJECTBUILD) GPE230_AndrewLong Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLong:
	 $(PROJECTBUILD) GPE230_AndrewLong Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLongEditor-Linux-Debug:
	 $(PROJECTBUILD) GPE230_AndrewLongEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLongEditor-Linux-DebugGame:
	 $(PROJECTBUILD) GPE230_AndrewLongEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLongEditor-Linux-Shipping:
	 $(PROJECTBUILD) GPE230_AndrewLongEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLongEditor-Linux-Test:
	 $(PROJECTBUILD) GPE230_AndrewLongEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

GPE230_AndrewLongEditor:
	 $(PROJECTBUILD) GPE230_AndrewLongEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
